# This is a basic workflow to help you get started with Actions

name: test_CI

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     -  'lean-lede/x86_64/.config'
  #schedule:
  #      - cron: 0 */6 * * *

jobs:
  x86:
    runs-on: ubuntu-latest
    steps:    
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        bash <(curl -fsSL https://raw.githubusercontent.com/ythyty/My-action/master/lean-lede/prenv.sh)
        
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        repository: coolsnowwolf/lede
        
    - name: Download and Load custom configuration
      run: |
        curl -fsSL https://raw.githubusercontent.com/ythyty/My-action/master/lean-lede/x86_64/.config >.config
        bash <(curl -fsSL https://raw.githubusercontent.com/ythyty/My-action/master/lean-lede/diy.sh)
        make defconfig
        
    - name: Download package
      run: |
        make download -j8
        find dl -size -1024c -exec rm -f {} \;
        sudo df -h
        
    
